### ISSUE TITLE
ConLL format also labelling the next word of the annotated part of the text

### ISSUE THREAD

**Issue by harunkuf** [doccano/doccano-transformer#21]
Hello, sorry for the other issue I accidentally created it.

After converting to ConLL format I get mislabeled "I-entity" tags. For example: "Obama was the president" results in [B-Person, I-Person, O, O] when it should be [B-Person, O, O, O]. 

I looked around at the original json1 data and found that this is due to the space after the entity being included in the tag. So instead of "Obama", the original tag is "Obama ", which results in the next word being included as an entity with this module. Is there anyway to get around taht without fixing the original json1 data? I have a lot of data that is already tagged and I can't imagine relabelling each one of them one by one.

If this can't be adressed within your module, can you give me tips on how to edit the original json1 file? I can maybe substract 1 from the end of the annotated part of the text. Thanks!

**Comment by icoxfog417** [comment]
It would be efficient to fix it before the transform or after the transform.
Is there any reason why you want to insert the module to fix the error in the transform process?

**Comment by harunkuf** [comment]
Sorry I forgot to update. I found that it's a lot better to fix it before the transform. In python, using the json library, readt the data and put it into the format where each line is a list element. So you have a list of dictionaries. Then iterate over the list elements, and for each list element, iterate over the "labels" key, and for each element of "labels" key, see if the start index of the label equals to sapce character (where label[n][0] == " "). Then also do the same thing for the end index of the label. Then just save list as a json file.
